apiVersion: 'serving.knative.dev/v1'
kind: 'Service'
metadata:
  name: 'has-default-prod'
spec:
  template:
    spec:
      containers:
        - image: 'has-default'
          env:
            - name: 'IAT_ISSUER_URL'
              value: 'https://has-default-prod-6kscuiwoba-an.a.run.app/indefiniteAccessToken/issue'
            - name: 'IAT_SIGNING_KMS_VERSION_NAME'
              value: 'projects/obs-plugin-voice-storage/locations/global/keyRings/has-default/cryptoKeys/has-indefinite-key-signing-20240814/cryptoKeyVersions/1'
            - name: 'CORS_ORIGINS'
              value: 'https://obs-plugin-voice-storage.firebaseapp.com https://obs-plugin-voice-storage.web.app http://localhost:5173'
            - name: 'AR_BUCKET_NAME'
              value: 'audiorecord-obs-plugin-voice-storage'
            - name: 'BASE_URL'
              value: 'https://has-3jd67qj8.an.gateway.dev'
      serviceAccountName: 'has-run@obs-plugin-voice-storage.iam.gserviceaccount.com'
